# Generated by Django 5.2.2 on 2025-06-08 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='menus/'),
        ),
    ]
