# Generated by Django 5.2.2 on 2025-06-12 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_menu_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='destacado',
            field=models.BooleanField(default=False),
        ),
    ]
