# Generated by Django 5.2.2 on 2025-06-17 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_menu_destacado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='creado_en',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
