# Generated by Django 5.2.2 on 2025-06-30 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0004_alter_menu_creado_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
