# Generated by Django 5.2.2 on 2025-07-02 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0005_menu_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
