# Generated by Django 5.2.2 on 2025-07-03 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0006_alter_menu_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='nombre',
            field=models.CharField(error_messages={'unique': 'Ya existe un menú con ese nombre.'}, max_length=100, unique=True),
        ),
    ]
