# Generated by Django 5.2.2 on 2025-07-01 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0002_recompensacanjeada'),
    ]

    operations = [
        migrations.AddField(
            model_name='recompensacanjeada',
            name='estado_entrega',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('entregado', 'Entregado')], default='pendiente', max_length=20),
        ),
    ]
