# Generated by Django 5.2.2 on 2025-07-03 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0003_recompensacanjeada_estado_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='recompensa',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
