# Generated by Django 5.2.2 on 2025-06-20 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_total_orderitem_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pago_verificado',
            field=models.BooleanField(default=False),
        ),
    ]
