# Generated by Django 5.2.2 on 2025-07-01 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_pago_verificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='stock_descuentado',
            field=models.BooleanField(default=False),
        ),
    ]
